### ISSUE TITLE
[New Feature]: Having field description

### ISSUE THREAD

**Issue by willcastillo** [199ocero/radio-deck#15]
### What happened?

Hey.. Thanks for this plugin. It'd be great if we could add a description for the field.

### How to reproduce the bug

Not a bug. Trying to access github's submit idea for this repo throws a 404

### Package Version

2

### PHP Version

8.2

### Laravel Version

11

**Comment by willcastillo** [comment]
FTR: I'm talking about a description for the field, not the individual icons.

**Comment by 199ocero** [comment]
> FTR: I'm talking about a description for the field, not the individual icons.

Hi! In my understanding is it description under the label of the field?

**Comment by willcastillo** [comment]
![image](https://github.com/199ocero/radio-deck/assets/1260357/5f9a87a3-80dc-4bd0-b70e-7f8a7f93e7a7)

Yes, in this capture, right below "Channel"

**Comment by 199ocero** [comment]
Will add this in to do list. Thanks for suggestion @willcastillo

**Comment by willcastillo** [comment]
No, thank YOU @199ocero !
