### ISSUE TITLE
[Bug]: Border outline color not working

### ISSUE THREAD

**Issue by CodeWithDennis** [199ocero/radio-deck#2]
### What happened?

In the new version the following method does not add a outline color to the options anymore `->color('primary')`. Downgrading to `v1.0.0-beta` does work.

### How to reproduce the bug

Add `->color('primary')` to the field. (or any other color)

### Package Version

v1.1.0

### PHP Version

v8.2

### Laravel Version

v10.39

### Notes

What is happening:
<img width="870" alt="Scherm­afbeelding 2024-01-02 om 14 37 47" src="https://github.com/199ocero/radio-deck/assets/23448484/608d7128-77cd-4fd7-b65b-77ccfe2942d5">

Expected behavior:
<img width="863" alt="Scherm­afbeelding 2024-01-02 om 14 38 27" src="https://github.com/199ocero/radio-deck/assets/23448484/8de4e197-2bef-4002-87bf-aee2612bd7c9">

**Comment by 199ocero** [comment]
Fix on latest release [v1.1.1](https://github.com/199ocero/radio-deck/releases/tag/v1.1.1)

**Comment by helio-cg** [comment]
I'm using custom theme. I noticed that the content vendor must be placed in the custom theme's tailwind config
