### ISSUE TITLE
[Bug]: Border select not work

### ISSUE THREAD

**Issue by a21ns1g4ts** [199ocero/radio-deck#24]
### What happened?

The selection border is not working. I've tried several ways and couldn't get it to work. Could something be missing from the documentation?  
![EAD](https://github.com/user-attachments/assets/1a092299-a53f-4472-b9f6-2f85adafe150)

### How to reproduce the bug

"filament/filament": "^3.1",
"php": "^8.1",

### Package Version

1.2

### PHP Version

8.2

### Laravel Version

11.0

### Which operating systems does with happen with?

Linux

**Comment by 199ocero** [comment]
Hi @a21ns1g4ts  did you create a custom theme and add the view in the tailwind config? [Installtion](https://github.com/199ocero/radio-deck?tab=readme-ov-file#installation)

**Comment by a21ns1g4ts** [comment]
@199ocero Is there another way where you don't need to do this? I'm not sure if this is really something worth depending on. I haven't looked at your implementation, so I can't judge it well. But if I have some time, I can check if there's a way to make it work without relying on using a custom theme. If you've already tried to solve this and couldn't due to some limitation, could you let me know?

**Comment by 199ocero** [comment]
Unfortunately @a21ns1g4ts  this is the only way for now to be able to render the styles of the component even the big plugins in Filament they all use custom theme.

**Comment by hanifwidiwidodo** [comment]
I experienced the same thing, even though I was using a custom theme. There is no complete documentation, or at least a video
