### ISSUE TITLE
[Bug]: Border outline color not working again

### ISSUE THREAD

**Issue by miguilimzero** [199ocero/radio-deck#9]
### What happened?

I'm having the same problem as described at https://github.com/199ocero/radio-deck/issues/2.

### How to reproduce the bug

Trying with any color reproduces the bug. I already verified and my `tailwind.config.js` content list is correct.

Maybe some breaking change with Filament v3.2? 

### Package Version

1.2.1

### PHP Version

8.2

### Laravel Version

10

### Which operating systems does with happen with?

Linux

**Comment by miguilimzero** [comment]
Not working on both light and dark theme:

![image](https://github.com/199ocero/radio-deck/assets/35383529/661c1bbc-3436-4a9c-8038-956028f46fd0)
![image](https://github.com/199ocero/radio-deck/assets/35383529/f396a6ac-8083-47b7-93be-3d3082f3f8df)

**Comment by 199ocero** [comment]
Hi @miguilimzero I can confirm that this is working with latest filament

![image](https://github.com/199ocero/radio-deck/assets/57591686/c908be63-376b-40f7-87a4-481f8b5f7f6f)

Maybe you miss a configuration. Please see this issue: [#8](https://github.com/199ocero/radio-deck/issues/8)

**Comment by miguilimzero** [comment]
It seems I was missing the filament preset on tailwind.config.js. The strange thing is that only the outline color was not working; everything else was fine. Thanks for the support @199ocero!
